name: pildora_biblica_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (necesario siempre)
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^5.10.0
  # firebase_storage: ^12.0.0
  # firebase_messaging: ^15.0.1

  share_plus: ^7.2.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fondo_amanecer.png
    - assets/fondo1_pb_t1.jpg
    - assets/fondo2_pb_t1.jpg
    - assets/fondo3_pb_t1.jpg
    - assets/logo_pildora.png
